Created the validation of the models
richie1988/blog-app pull request #5
Opened 2023-12-07 14:36 UTC by richie1988

## Project requirements

- [ ] Use validations for models.
- [ ] Write unit tests for models.

## For the User model:
Name must not be blank.
PostsCounter must be an integer greater than or equal to zero.
## For the Post model:

- Title must not be blank.
- Title must not exceed 250 characters.
- CommentsCounter must be an integer greater than or equal to zero.
- LikesCounter must be an integer greater than or equal to zero.

## Added unit specs for all of My models' methods and validations.
- User model:
- Post model:

2023-12-07 20:28 UTC, tresorsawasawa reviewed
# STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @richie1988 :wave: :wave: 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑 🛑

You have submitted a project where all linters are not passing.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

---
Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

---
_Invalid Code Review Request **Does not count** into the code reviews limit._

2023-12-07 21:13 UTC, omar-muhamad requested changes
# Changes Required ♻️
### Hi @richie1988,

### Nice job, you are almost there.

![giphy (2)](https://user-images.githubusercontent.com/68796232/223284713-d4ea97f0-5ad2-438b-8ac5-1481a991da3f.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- [ ] Please check the inline comments below ⬇️.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-12-07 21:13 UTC, omar-muhamad commented on spec/models/user_spec.rb
> +  # Add more tests as needed
- [ ] [Required] Nice job adding validation tests for `user` and `post` models, As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_validations_model_spec.md#:~:text=Add%20unit%20specs%20for%20all%20of%20your%20models%27%20methods%20and%20validations.), Please add unit tests for methods inside all models (user, post, comment, and like).
- [ ] [Optional] [Highly recommended] Please include all the validation tests inside a `describe` method, So tests look more arranged and professional.

2023-12-07 21:13 UTC, omar-muhamad commented on spec/models/post_spec.rb
> +  it { should validate_numericality_of(:likes_counter).only_integer.is_greater_than_or_equal_to(0) }
- [ ] [Optional] [Highly recommended] Same here, It would be better professionally if you include all validation tests inside a `describe` method. 
```suggestion
describe 'validations' do
  it { should validate_presence_of(:title) }
  it { should validate_length_of(:title).is_at_most(250) }
  it { should validate_numericality_of(:comment_counter).only_integer.is_greater_than_or_equal_to(0) }
  it { should validate_numericality_of(:likes_counter).only_integer.is_greater_than_or_equal_to(0) }
end

describe 'methods' do
  -------
  -------
end
```

2023-12-08 01:32 UTC, Efiamotu-1 requested changes
Hi @richie1988, 

![](https://camo.githubusercontent.com/a06454929d29b512682cd8b375641b59076b9e5fe1a367808e685e5bcb818de3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45784e32466d5957466c5a6a45794d7a49314f4455784d5455775a44686b595459355932526c4e6a4d334e7a4e6c4f574530596a4a684d695a6c634431324d563970626e526c636d35686246396e61575a7a583264705a6b6c6b4a6d4e305057632f7a3370696f6b77663057504838314d4f68752f67697068792e676966)

Great work on making the changes requested by a previous reviewer 👏 Your Code is Awesome! 💪
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-08 01:32 UTC, Efiamotu-1 commented on spec/models/comment_spec.rb
- [ ] Good job adding the tests as requested by the  previous reviewer, however when i run your test for the comments, they are failing due to syntax error as shown in the image below, please kindly fix this :+1: 
![sy-1](https://github.com/richie1988/blog-app/assets/89055502/f4c199f0-0d1f-4a79-bd2a-20e085756da6)

2023-12-08 01:32 UTC, Efiamotu-1 commented on spec/models/like_spec.rb
- [ ] Good job adding the tests as requested by the  previous reviewer, however when i run your test for the likes, they are failing due to syntax error as shown in the image below, please kindly fix this :+1: 
![l-2](https://github.com/richie1988/blog-app/assets/89055502/e467120f-f75e-4c8e-8143-463ab2cfc08b)

2023-12-08 01:32 UTC, Efiamotu-1 commented on spec/models/post_spec.rb
- [ ] Good job adding the tests as requested by the  previous reviewer, however when i run your test for the posts, they are failing due to syntax error as shown in the image below, please kindly fix this :+1: 
![p-3](https://github.com/richie1988/blog-app/assets/89055502/ad686dd7-d49a-4c8b-ae18-28e20194295e)

2023-12-08 01:32 UTC, Efiamotu-1 commented on spec/models/user_spec.rb
- [ ] Good job adding the tests as requested by the  previous reviewer, however when i run your test for the users, they are failing due to syntax error as shown in the image below, please kindly fix this :+1: 
![u-4](https://github.com/richie1988/blog-app/assets/89055502/87060d95-f030-4481-98cb-417762376d4f)

2023-12-08 13:27 UTC, closed without merging